import type { Metadata } from "next";
import ProtectedRoute from "@/components/shared/ProtectedRoute";

export const metadata: Metadata = {
  title: "HabiLog - Habit Tracker PWA",
  description: "Generated by Habit Tracker PWA",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ProtectedRoute>{children}</ProtectedRoute>;
}
